[phases.setup]
aptPkgs = [
  "poppler-utils",   # For pdf2image
  "tesseract-ocr",   # For pytesseract
  "libgl1",          # For OpenCV (fixes your error)
  "libglib2.0-0",    # Required by OpenCV on some builds
  "gcc",             # For compiling any Python packages
  "ffmpeg"           # Optional: used by torch/media
]

[start]
cmd = "gunicorn wsgi:app --bind 0.0.0.0:$PORT"
