[phases.setup]
aptPkgs = [
  "poppler-utils",   # For pdf2image
  "tesseract-ocr",   # For pytesseract
  "gcc",             # For compiling dependencies
  "ffmpeg"           # Optional, for torch/media
]

[start]
cmd = "gunicorn wsgi:app --bind 0.0.0.0:$PORT"
